### PR TITLE
This website clone is ready for production

### PR DESCRIPTION
**Pull request by emasdev**
In this project we:

- Create a website clone of a New York Times article
- It has a header and a footer with navigation elements
- A main section with the article content
- Embedded Images and video
- A sidebar with links for other articles
- A signup section inside the article content
- A grid with extra data and images

### CODE REVIEW

**Comment by emasdev** [comment]
- Install Stickler in this repo
- Fixed style.css to DRY
- Add mails to README
- Add live link

**Comment by harshdeep-kanhai** [comment]
resubmit it for review.

**Comment by emasdev** [comment]
We have some problems with the stickler because it throws some errors that are not errors, for example, we are using grid and it throws this error: Error - Unexpected token '1fr' at line 76, col 26. (errors)

there some warnings about alphabetical order properties in the CSS file, we use sass so the build for the CSS was built automatically. I think Stickler's validator is very strict. Can we remove these warnings?

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 
## Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

- [ ]  :one: You need to [Set-up Linter](https://github.com/microverseinc/linters-config/tree/master/css) in order to get this project approved.
  > I can see that you had added a stickler file but your PR is not running through the checks, I recommend you guys to check the [stickler](https://stickler-ci.com/) page to see if you had activated your project in there.

## Here are some details you have to get fix before asking for another code review

#### Editors Pick
- [ ]  Images keep braking up as my college commented before
### Requirement
Screenshot from 2020-04-09 19-55-38
### Yours
Screenshot from 2020-04-09 19-54-42

#### Editors Pick
- [ ]  Images keep braking up as my college commented before
### Requirement
Screenshot from 2020-04-09 19-55-38
### Yours
Screenshot from 2020-04-09 19-54-42


## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes :red_circle:
### Hey :wave: 
## Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

- [ ]  :one: You need to [Set-up Linter](https://github.com/microverseinc/linters-config/tree/master/css) in order to get this project approved.
  > I can see that you had added a stickler file but your PR is not running through the checks, I recommend you guys to check the [stickler](https://stickler-ci.com/) page to see if you had activated your project in there.

## Here are some details you have to get fix before asking for another code review

#### Editors Pick
- [ ]  Images keep braking up as my college commented before
### Requirement
Screenshot from 2020-04-09 19-55-38
### Yours
Screenshot from 2020-04-09 19-54-42

#### Images Description
- [ ]  The description of all your images is braking up. here an example of one of them
### Requirement
Screenshot from 2020-04-09 19-56-01
### Yours
Screenshot from 2020-04-09 19-54-02

#### Video & Images
- [ ] It contains centered text and images ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
### Requirement
Screenshot from 2020-04-09 19-55-12
### Yours
Screenshot from 2020-04-09 19-54-27

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by uryelah** [comment]
Hello **Emanuel González Irigoyen** & **Kanhai Kanhai**, I'm Sarah, your reviewer for this PR 👩‍🚀  

You are almost there, the project is just missing a couple of hard requirements to be fulfilled.

You've come a long way since the first review and even managed to fix those annoying stickler errors so I'm sure you can nail this down! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] The page is missing its fixed footer. Check the screencap below for how it should look:
Screenshot_2020-04-10 Space Ripples Reveal Big Bang’s Smoking Gun

---- 

- Make sure there are no errors or warnings in your[ HTML validation.](https://validator.w3.org/nu)

------

- [ ] The page text should be centered. Yours is leaning to the left:
Screenshot_2020-04-10 The Newyork Times Space Ripples Reveal Big Bang’s Smoking Gun

----

- [ ] For some reason the icons in the 'Subscribe' area are not loading correctly:
Screenshot_2020-04-10 The Newyork Times Space Ripples Reveal Big Bang’s Smoking Gun(1)

-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
